### ISSUE TITLE
'dict_values' object has no attribute 'sort'

### ISSUE THREAD

**Issue by cometsong** [Alir3z4/django-databrowse#37]
**Versions:**
> Python: 3.6.1
> Django: 1.11.9
> Databrowse: updated along with mods from ccnmtl plus others.

**Actions:**
When viewing object list page sorted by a field, then tried clicking on the 'Fields' breadcrumbs link and got this error.

**Traceback:**  (note: the "id_generate/jaxiddetail" is the app/model name and the "parent_jaxid" is the currently chosen sort field.)
```python

Internal Server Error: /databrowse/id_generate/jaxiddetail/fields/, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
Traceback (most recent call last):, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    response = get_response(request), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    response = self.process_exception_by_middleware(e, request), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    response = wrapped_callback(request, *callback_args, **callback_kwargs), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/src/databrowse/django_databrowse/sites.py", line 162, in root, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    return self.model_page(request, *url.split('/', 2)), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/src/databrowse/django_databrowse/sites.py", line 191, in model_page, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    return databrowse_class(model, self).root(request, rest_of_url), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/src/databrowse/django_databrowse/sites.py", line 73, in root, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    return plugin.model_view(request, self, rest_of_url), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/src/databrowse/django_databrowse/plugins/fieldchoices.py", line 76, in model_view, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    return self.homepage_view(request), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
  File "/var/www/apps/src/databrowse/django_databrowse/plugins/fieldchoices.py", line 90, in homepage_view, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
    field_list.sort(key=lambda k: k.verbose_name), /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
AttributeError: 'dict_values' object has no attribute 'sort', /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
, /databrowse/id_generate/jaxiddetail/fields/parent_jaxid/
```

**Comment by cometsong** [comment]
Turns the [.values](https://docs.python.org/3/library/stdtypes.html?#dict-views) method on a dict returns a `view` instead of `list`. 
So to sort, the code in [plugins/fieldchoices.py#L89](https://github.com/Alir3z4/django-databrowse/blob/master/django_databrowse/plugins/fieldchoices.py#L89)
needs to be changed from:
`field_list = self.fields.values()`
to:
`field_list = list(self.fields.values())`
to have the `.sort()` method available.
